import type { Engagement, TimelineEvent } from "./types";

export const demoEngagements: Engagement[] = [
  {
    id: "eng-1001",
    clientId: "client-1001",
    clientName: "ABC Manufacturing",
    engagementNumber: "ENG-2026-1001",
    taxYear: 2026,
    status: "IN_PROGRESS",
    currentStage: "REVIEW",
    owner: "John Smith",
    dueDate: "2026-10-15",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-09-10T09:00:00Z",
    stages: [
      { stageKey: "PROSPECT", stageName: "Prospect", status: "COMPLETED" },
      { stageKey: "PROPOSAL", stageName: "Proposal", status: "COMPLETED" },
      { stageKey: "ENGAGEMENT_LETTER", stageName: "Engagement Letter", status: "COMPLETED" },
      { stageKey: "DOCUMENT_COLLECTION", stageName: "Document Collection", status: "COMPLETED" },
      { stageKey: "PREPARATION", stageName: "Preparation", status: "COMPLETED" },
      { stageKey: "REVIEW", stageName: "Review", status: "IN_PROGRESS" },
      { stageKey: "FILING", stageName: "Filing", status: "PENDING" },
      { stageKey: "BILLING", stageName: "Billing", status: "PENDING" },
      { stageKey: "PAYMENT", stageName: "Payment", status: "PENDING" },
      { stageKey: "RENEWAL", stageName: "Renewal", status: "PENDING" },
    ],
  },
  {
    id: "eng-1002",
    clientId: "client-1002",
    clientName: "XYZ Corporation",
    engagementNumber: "ENG-2026-1002",
    taxYear: 2026,
    status: "IN_PROGRESS",
    currentStage: "PREPARATION",
    owner: "Sarah Lee",
    dueDate: "2026-10-20",
    createdAt: "2026-08-15T10:00:00Z",
    updatedAt: "2026-09-09T13:00:00Z",
    stages: [],
  },
  {
    id: "eng-1003",
    clientId: "client-1003",
    clientName: "Northwind Logistics",
    engagementNumber: "ENG-2026-1003",
    taxYear: 2026,
    status: "COMPLETED",
    currentStage: "PAYMENT",
    owner: "Mike Brown",
    dueDate: "2026-09-30",
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-09-05T13:00:00Z",
    stages: [],
  },
];

export const demoTimeline: Record<string, TimelineEvent[]> = {
  "eng-1001": [
    {
      id: "evt-1",
      stageKey: "PROPOSAL",
      title: "Proposal approved",
      status: "COMPLETED",
      timestamp: "2026-08-05T10:00:00Z",
      actor: "John Smith",
    },
    {
      id: "evt-2",
      stageKey: "DOCUMENT_COLLECTION",
      title: "Documents collected",
      status: "COMPLETED",
      timestamp: "2026-08-28T14:30:00Z",
      actor: "Operations Team",
    },
    {
      id: "evt-3",
      stageKey: "PREPARATION",
      title: "Preparation completed",
      status: "COMPLETED",
      timestamp: "2026-09-04T16:00:00Z",
      actor: "Sarah Lee",
    },
    {
      id: "evt-4",
      stageKey: "REVIEW",
      title: "Review started",
      status: "IN_PROGRESS",
      timestamp: "2026-09-08T09:30:00Z",
      actor: "Mike Brown",
    },
  ],
};
